---

- name: Download EPEL RPM
  get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
- name: install EPEL rpm
  yum: pkg=/tmp/epel-release.rpm state=installed
- name: install pip
  yum: pkg=python-pip state=installed

- name: python development install
  yum: pkg={{ item }} state=installed
  with_items:
    - python-devel
    - libxslt-devel
    - libxml2-devel

- name: Install new SSH banner
  template: src=motd.j2 dest=/etc/motd
