---

- name: Configure and deploy combined webserver/database test server
  hosts: all

  vars_files:
    - vars/main.yml

  remote_user: vagrant

  roles:
    - common
    - {role: web, tags: http}
    - {role: db, tags: mysql }